services:
  backend:
    image: nutricart-backend-test
    container_name: nutricart-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/nutricart.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nutricart-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nutricart-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nutricart-network

  # Backend test service
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: nutricart-backend-test
    volumes:
      - ./backend:/app
      - test_coverage:/app/htmlcov
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./test.db
      - PYTEST_ARGS=${PYTEST_ARGS:---verbose}
    command: pytest tests ${PYTEST_ARGS:---verbose}
    depends_on:
      - backend
    networks:
      - nutricart-network
    profiles:
      - test

  # Test with coverage service
  backend-test-coverage:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: nutricart-backend-test-coverage
    volumes:
      - ./backend:/app
      - test_coverage:/app/htmlcov
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./test.db
    command: pytest tests --cov=app --cov-report=html --cov-report=term --verbose
    depends_on:
      - backend
    networks:
      - nutricart-network
    profiles:
      - test

volumes:
  backend_data:
    driver: local
  test_coverage:
    driver: local

networks:
  nutricart-network:
    driver: bridge
